version: "3.8"
services:
  api:
    build: .
    command: python3 main.py
    ports:
      - "5000:5000"
    volumes:
      - .:/flask-api
    depends_on:
      - database
    restart: always
  database:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketplace_db