version: "3.8"
services:
  api:
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/flask-api
    depends_on:
      - database
    env_file: .env
    restart: always
  database:
    image: mysql:5.6
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
    env_file: .env